export default [
  {
    title: 'Escritorio',
    to: { name: 'dashboard' },
    permission: 'all',
    icon: { icon: 'ri-pie-chart-box-line' },
  },
  { heading: 'Catalogo SIAT' },
  {
    title: 'Clientes',
    to: { name: 'second-page' },
    permission: 'listar_cliente',
    icon: { icon: 'ri-user-3-line' },
  },
  {
    title: 'Productos/Servicios',
    to: { name: 'second-page' },
    permission: 'listar_producto',
    icon: { icon: 'ri-list-ordered-2' },
  },
  { heading: 'Gestión Operativa' },
  {
    title: 'Contratos',
    to: { name: 'second-page' },
    permission: 'listar_contrato',
    icon: { icon: 'ri-file-pdf-2-fill' },
  },
  {
    title: 'Gestiones (ABMs)',
    to: { name: 'second-page' },
    permission: 'listar_abm',
    icon: { icon: 'ri-file-edit-fill' },
  },
  {
    title: 'Adendas y Modificaciones',
    to: { name: 'second-page' },
    permission: 'listar_adenda',
    icon: { icon: 'ri-pages-line' },
  },
  { heading: 'Facturación SIAT' },
  {
    title: 'Emisión de Facturas',
    to: { name: 'second-page' },
    permission: 'listar_factura',
    icon: { icon: 'ri-draft-line' },
  },
  {
    title: 'Puntos de Venta / Sucursales',
    to: { name: 'second-page' },
    permission: 'listar_sucursal',
    icon: { icon: 'ri-store-2-line' },
  },
  {
    title: 'Sincronización con SIAT',
    to: { name: 'second-page' },
    permission: 'sincronizacion',
    icon: { icon: 'ri-refresh-line' },
  },
  { heading: 'Reportes' },
  {
    title: 'Reporte por cliente',
    icon: { icon: 'ri-folder-chart-line' },
    permission: 'reportes',
    to: { name: 'second-page' },
  },
  {
    title: 'Reporte de Ingresos',
    icon: { icon: 'ri-money-cny-circle-line' },
    permission: 'reportes',
    to: { name: 'second-page' },
  },
  { heading: 'Configuración y Accesos' },
  {
    title: 'Usuarios',
    to: { name: 'second-page' },
    permission: 'listar_usuario',
    icon: { icon: 'ri-user-settings-line' },
  },
  {
    title: 'Roles y Permisos',
    to: { name: 'roles-permisos' },
    permission: 'listar_rol',
    icon: { icon: 'ri-lock-password-line' },
  },
  {
    title: 'Configuración SIAT',
    to: { name: 'second-page' },
    permission: 'configuracion',
    icon: { icon: 'ri-settings-3-line' },
  }
]
